inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - config/initializers/devise.rb
    - config/initializers/simple_form.rb
